// Verified semantic matches from the live Striver sheet and official TUF sitemap.
// Question IDs are used where the old tracker title differs from the article title.
const officialArticleByQuestionId = {
    '1_print_name_n_times_using_recursion':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/print-name-n-times-using-recursion',
    '2_print_1_to_n_using_recursion':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/print-1-to-n-using-recursion',
    '3_print_n_to_1_using_recursion':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/print-n-to-1-using-recursion',
    '5_factorial_of_n_numbers':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/factorial-of-a-number',
    '6_reverse_and_array':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/reversing-an-array-using-recursion',
    '0_count_frequencies_of_array_elements':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/hashing-data-structures',
    added_2_count_subarrays_with_given_sum:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/count-subarrays-with-given-sum',
    '8_find_the_union_and_intersection_of_two_sorted_arrays':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/union-of-two-sorted-arrays',
    '1_second_largest_element_in_an_array_without_sorting':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/second-largest-element',
    '5_left_rotate_an_array_by_d_places':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/left-rotate-array-by-k-places',
    '7_linear_search':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/linear-search-algorithm',
    '9_find_missing_number_in_an_array':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/missing-number',
    '12_find_the_missing_number':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/missing-number',
    '13_find_the_number_that_appears_once,_and_other_numbers_twice.':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/single-number-i',
    '5_stock_buy_and_sell':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/best-time-to-buy-and-sell-stock',
    added_0_pascal_s_triangle_ii:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/pascal-triangle-ii',
    added_1_pascal_s_triangle_iii:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/pascals-triangle-first-n-rows',
    '15_find_the_row_with_maximum_number_of_1’s':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/find-the-row-with-maximum-1s-in-a-sorted-binary-matrix',
    '1_implement_lower_bound':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/lower-bound-in-sorted-array',
    '2_implement_upper_bound':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/upper-bound-in-sorted-array',
    '13_find_out_how_many_times_has_an_array_been_rotated':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/rotation-count-sorted-array',
    '0_search_in_a_2d_matrix_':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/search-in-a-row-and-column-wise-sorted-matrix',
    '11_single_element_in_a_sorted_array':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/single-element-in-a-sorted-array',
    '8_book_allocation_problem':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/book-allocation-problem',
    '4_check_if_input_array_is_sorted':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/check-if-an-array-is-sorted-in-ascending-order',
    '6_median_of_two_sorted_arrays':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/median-of-2-sorted-arrays',
    '0_sort_characters_by_frequency':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/sort-characters-by-frequency',
    '2_hashing_in_strings_|_theory':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/string-hashing-rolling-hash',
    '3_rabin_karp':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/introduction-to-pattern-matching-algorithm',
    '5_kmp_algo_/_lps(pi)_array':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/introduction-to-pattern-matching-algorithm',
    '2_count_good_numbers':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/count-good-numbers',
    added_0_single_number_ii:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/single-number-ii',
    '2_minimum_window_substring':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/minimum-window-substring',
    added_0_sliding_window_two_pointer_theory:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/two-pointer-introduction',
    '5_task_scheduler':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/task-scheduler',
    '0_kth_largest_element_in_an_array_[use_priority_queue]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/k-th-largest-element-in-an-array',
    '3_merge_m_sorted_lists':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/merge-k-sorted-linked-lists',
    added_2_heap_sort:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/heap-sort',
    '0_assign_cookies':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/assign-cookies',
    '1_find_peak_element_':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/find-peak-element-2d-matrix',
    '0_introduction_to_linkedlist,_learn_about_struct,_and_how_is_node_represented_':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    '0_introduction_to_dll,_learn_about_struct,_and_how_is_node_represented_':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    '11_sort_a_ll_of_0’s_1’s_and_2’s_by_changing_links':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/sort-linked-list-0s-1s-2s-changing-links',
    '13_add_1_to_a_number_represented_by_ll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/add-one-to-number-linked-list',
    '9_delete_the_middle_node_of_ll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/delete-the-middle-node-of-a-linked-list',
    '7_divide_two_integers_without_using_multiplication,_division_and_mod_operator':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/divide-two-integers-without-multiplication-division-modulo',
    '3_find_xor_of_numbers_from_l_to_r':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/xor-of-numbers-in-a-range-l-to-r',
    '1_jump_game':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/jump-game',
    '2_jump_game_2':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/jump-game-ii-minimum-jumps',
    '7_maximum_point_you_can_obtain_from_cards':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/maximum-points-you-can-obtain-from-cards',
    '6_number_of_substring_containing_all_three_characters':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/count-substrings-containing-all-three-characters-a-b-and-c',
    '4_binary_subarray_with_sum':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/binary-subarrays-with-sum',
    '1_subarray_with_k_different_integers':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/subarrays-with-k-different-integers',
    '1_next_greater_element_-_ii':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/next-greater-element-ii-circular-array',
    '5_sum_of_subarray_minimum':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/sum-of-subarray-minimums',
    '4_print_all_the_nodes_at_a_distance_of_k_in_a_binary_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/nodes-distance-k-binary-tree',
    '5_minimum_time_taken_to_burn_the_binary_tree_from_a_node':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/minimum-time-burn-binary-tree',
    '7_requirements_needed_to_construct_a_unique_binary_tree_|_theory':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/requirements-needed-to-construct-a-unique-binary-tree',
    '0_introduction_to_binary_search_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/binary-search-tree',
    '1_search_in_a_binary_search_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/search-in-a-binary-search-tree',
    '0_ceil_in_a_binary_search_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/floor-and-ceil-in-a-bst',
    '1_floor_in_a_binary_search_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/floor-and-ceil-in-a-bst',
    '12_largest_bst_in_binary_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/largest-bst-in-binary-tree',
    '3_course_schedule_–_i':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/course-schedule-i',
    '4_course_schedule_–_ii':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/course-schedule-ii',
    '5_find_eventual_safe_states':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/find-eventual-safe-states',
    '7_network_delay_time':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/network-delay-time',
    '10_bellman_ford_algorithm':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/bellman-ford-algorithm',
    '9_making_a_large_island':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/making-a-large-island',
    added_0_print_shortest_path:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/print-shortest-path',
    '1_connected_components_problem_in_matrix':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/number-of-provinces',
    '4_cycle_detection_in_unirected_graph_(bfs)':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/detect-a-cycle-in-an-undirected-graph',
    '5_cycle_detection_in_undirected_graph_(dfs)':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/detect-a-cycle-in-an-undirected-graph',
    '11_number_of_distinct_islands_[dfs_multisource]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/number-of-distinct-islands',
    '13_cycle_detection_in_directed_graph_(dfs)':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/detect-a-cycle-in-a-directed-graph',
    '2_cycle_detection_in_directed_graph_(bfs)':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/detect-a-cycle-in-a-directed-graph',
    '2_djisktra’s_algorithm':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/dijkstras-algorithm',
    '3_why_priority_queue_is_used_in_djisktra’s_algorithm':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/dijkstras-algorithm',
    '0_minimum_spanning_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/find-the-mst-weight',
    '1_prim’s_algorithm':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/prims-algorithm',
    '4_kruskal’s_algorithm':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/kruskals-algorithm-minimum-spanning-tree',
    '2_kosaraju’s_algorithm':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/kosarajus-algorithm',
    '0_shortest_path_in_ug_with_unit_weights':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/shortest-path-in-an-unweighted-undirected-graph-using-bfs',
    '9_word_ladder_–_1':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/word-ladder',
    '10_word_ladder_–_2':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/word-ladder-ii',
    '4_shortest_path_in_a_binary_maze':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/shortest-distance-binary-maze',
    '6_cheapest_flights_within_k_stops':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/cheapest-flights-within-k-stops',
    '9_minimum_steps_to_reach_end_from_start_by_performing_multiplication_and_mod_operations_with_array_elements':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/minimum-multiplications-to-reach-end',
    '12_find_the_city_with_the_smallest_number_of_neighbors_in_a_threshold_distance':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/find-city-smallest-number-neighbors-threshold-distance',
    '2_disjoint_set_[union_by_rank]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/disjoint-set-union',
    '3_disjoint_set_[union_by_size]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/disjoint-set-union',
    '6_most_stones_removed_with_same_rows_or_columns':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/most-stones-removed-same-row-column',
    '1_articulation_point':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/articulation-points-in-graph',
    '5_palindrome_partitioning_–_ii|(dp-53)':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/palindrome-partitioning-ii-minimum-cuts',
    '5_maximum_xor_with_an_element_from_array':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/maximum-xor-queries-trie',
    '2_number_of_distinct_substrings_in_a_string':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/number-of-distinct-substrings-in-a-string',
    '1_longest_string_with_all_prefixes':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/longest-word-with-all-prefixes',
    '4_z-function':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/z-function',
    '6_shortest_palindrome':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/shortest-palindrome',
    '2_deleting_a_node_in_linkedlist':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    '1_insert_a_node_in_dll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    '2_delete_a_node_in_dll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    '0_middle_of_a_linkedlist_[tortoise_hare_method]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/find-middle-of-linked-list',
    '1_reverse_a_linkedlist_[iterative]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/reverse-a-singly-linked-list',
    '2_reverse_a_ll_[recursive]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/reverse-a-singly-linked-list',
    '3_detect_a_loop_in_ll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/detect-cycle-linked-list',
    '7_segrregate_odd_and_even_nodes_in_ll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/segregate-odd-and-even-nodes-in-linked-list',
    '1_find_pairs_with_given_sum_in_dll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/find-pairs-with-given-sum-in-doubly-linked-list',
    '1_rotate_a_ll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/rotate-linked-list-right-k-places',
    '2_flattening_of_ll':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/flatten-linked-list',
    added_0_deletion_of_the_head_of_ll:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    added_1_deletion_of_the_tail_of_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    added_2_deletion_of_the_kth_element_of_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    added_3_delete_the_element_with_value_x:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    added_5_insertion_at_the_tail_of_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    added_6_insertion_at_the_kth_position_of_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    added_7_insertion_before_the_value_x_in_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/singly-linked-list',
    added_8_convert_array_to_doubly_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    added_9_delete_tail_of_doubly_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    added_10_delete_kth_element_of_doubly_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    added_11_removing_given_node_in_doubly_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    added_12_insert_node_before_head_in_doubly_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    added_13_insert_node_before_tail_in_doubly_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    added_14_insert_node_before_kth_node_in_doubly_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    added_15_insert_before_given_node_in_doubly_linked_list:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/doubly-linked-list',
    '1_pow(x,_n)':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/fast-power-one-shot-binary-exponentiation-modular-exponentiation-and-powx-n',
    '4_count_all_subsequences_with_sum_k':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/count-subsets-with-sum-k',
    '5_check_if_there_exists_a_subsequence_with_sum_k':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/subset-sum-equal-to-target',
    '0_introduction_to_bit_manipulation_[theory]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/bit-basics-and-operators',
    '1_check_if_the_i-th_bit_is_set_or_not':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/bit-basics-and-operators',
    '2_check_if_a_number_is_odd_or_not':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/check-even-or-odd',
    '3_check_if_a_number_is_power_of_2_or_not':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/bit-counting-tricks',
    '4_count_the_number_of_set_bits':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/bit-counting-tricks',
    '6_swap_two_numbers':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/bitwise-arithmetic',
    '0_count_number_of_bits_to_be_flipped_to_convert_a_to_b':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/bit-counting-tricks',
    '1_find_the_number_that_appears_odd_number_of_times':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/single-number-i',
    '4_find_the_two_numbers_appearing_odd_number_of_times':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/single-number-iii',
    '4_power(n,_x)':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/power-of-a-number-using-recursion',
    '0_introduction_to_priority_queues_using_binary_heaps':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/introduction-to-heap',
    '1_kth_smallest_element_in_an_array_[use_priority_queue]':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/k-th-smallest-element-in-an-array',
    '2_sort_k_sorted_array':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/merge-k-sorted-arrays',
    '2_kth_largest_element_in_a_stream_of_running_integers':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/kth-largest-element-stream',
    '4_find_median_from_data_stream':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/find-median-data-stream',
    '5_k_most_frequent_elements':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/top-k-frequent-elements',
    '4_valid_paranthesis_checker':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/check-balanced-parentheses-using-a-stack',
    '0_introduction_to_trees':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/binary-tree-data-structure',
    added_0_print_root_to_leaf_path_in_bt:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/print-root-to-leaf-path-in-binary-tree',
    '2_insert_a_given_node_in_binary_search_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/insert-into-a-binary-search-tree',
    '3_delete_a_node_in_binary_search_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/delete-node-in-a-bst',
    '5_check_if_a_tree_is_a_bst_or_bt':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/validate-binary-search-tree',
    '6_lca_in_binary_search_tree':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/lowest-common-ancestor-of-a-binary-search-tree',
    '7_construct_a_bst_from_a_preorder_traversal':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/construct-a-bst-from-preorder-traversal',
    '8_inorder_successor/predecessor_in_bst':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/inorder-successor-and-predecessor-in-a-bst',
    '10_two_sum_in_bst_|_check_if_there_exists_a_pair_with_sum_k':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/two-sum-in-bst',
    '11_recover_bst_|_correct_bst_with_two_nodes_swapped':
        'https://takeuforward.org/blogs/data-structure-and-algorithm/recover-binary-search-tree',
    added_0_bst_iterator:
        'https://takeuforward.org/blogs/data-structure-and-algorithm/binary-search-tree-iterator',
}

export default officialArticleByQuestionId
